### ISSUE TITLE
FAT

### ISSUE THREAD

**Issue by ihipoo1** [thaoshibe/awesome-makeup-transfer#1]
https://arxiv.org/abs/2104.02894
Check it)

**Comment by thaoshibe** [comment]
Aww, I'm so sorry for late reply. I didn't turn on notification for this repo (it's on now) ✺◟( ͡° ͜ʖ ͡°)◞✺.

Thank for your contribution! [[2104.02894](https://arxiv.org/abs/2104.02894)] added!!
