### ISSUE TITLE
SOGAN

### ISSUE THREAD

**Issue by Yueming6568** [thaoshibe/awesome-makeup-transfer#2]
hello, our ''SOGAN: 3D-Aware Shadow and Occlusion Robust GAN for Makeup Transfer'' is accepted by ACM MM2021.
This is the link of our paper:  https://arxiv.org/abs/2104.10567
thank you ~

**Comment by thaoshibe** [comment]
Sure, I added it!
And by the way, nice work! Feel free to ping if you release the code!
